# Generated by Django 4.0.6 on 2022-07-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_alter_category_id_alter_categoryrelation_id_and_more'), ('products', '0003_file'), ('products', '0004_remove_file_timestamp'), ('products', '0005_remove_categoryrelation_category_child_and_more'), ('products', '0006_offer_offer_vendor_code'), ('products', '0007_offer_offer_vat_product_product_color_and_more'), ('products', '0008_offer_offer_percent_product_product_lining_material_and_more'), ('products', '0009_product_product_photos')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=200)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.category')),
                ('product_brand', models.CharField(max_length=200)),
                ('product_article', models.CharField(max_length=200)),
                ('product_color', models.CharField(default=1, max_length=20)),
                ('product_heel_height', models.IntegerField(default=1)),
                ('product_height', models.IntegerField(default=1)),
                ('product_insole_material', models.CharField(default=1, max_length=30)),
                ('product_length', models.IntegerField(default=1)),
                ('product_manufacturer_Region', models.CharField(default=1, max_length=30)),
                ('product_sale_season', models.CharField(default=1, max_length=20)),
                ('product_season', models.CharField(default=1, max_length=20)),
                ('product_sex', models.CharField(default=1, max_length=10)),
                ('product_style', models.CharField(default=1, max_length=20)),
                ('product_style_Region', models.CharField(default=1, max_length=30)),
                ('product_type', models.CharField(default=1, max_length=20)),
                ('product_weight', models.IntegerField(default=1)),
                ('product_width', models.IntegerField(default=1)),
                ('product_lining_material', models.CharField(default=1, max_length=200)),
                ('product_sole_height', models.IntegerField(default=1)),
                ('product_sole_material', models.CharField(default=1, max_length=200)),
                ('product_upper_material', models.CharField(default=1, max_length=200)),
                ('product_vendor_color', models.CharField(default=1, max_length=20)),
                ('product_photos', models.TextField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_available', models.CharField(max_length=10)),
                ('offer_price', models.IntegerField()),
                ('offer_price_begin', models.IntegerField()),
                ('offer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_product', to='products.product')),
                ('offer_size', models.IntegerField()),
                ('offer_RU_size', models.IntegerField()),
                ('offer_vendor_code', models.CharField(default=1, max_length=20)),
                ('offer_vat', models.IntegerField(default=1)),
                ('offer_percent', models.IntegerField(default=1)),
            ],
        ),
    ]
