# Generated by Django 3.1.3 on 2022-07-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.category')),
                ('product_brand', models.CharField(max_length=200)),
                ('product_article', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_available', models.CharField(max_length=200)),
                ('offer_price', models.IntegerField()),
                ('offer_price_begin', models.IntegerField()),
                ('offer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_product', to='products.product')),
                ('offer_size', models.IntegerField()),
                ('offer_RU_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_child', to='products.category')),
                ('category_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_parent', to='products.category')),
            ],
        ),
    ]
