# Generated by Django 4.0.6 on 2022-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_file_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryrelation',
            name='category_child',
        ),
        migrations.RemoveField(
            model_name='categoryrelation',
            name='category_parent',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_available',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CategoryRelation',
        ),
    ]
