# Generated by Django 4.0.6 on 2022-07-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_categoryrelation_category_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_vendor_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
