# Generated by Django 4.0.6 on 2022-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_offer_offer_vat_product_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_lining_material',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_sole_height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_sole_material',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_upper_material',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_vendor_color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
