# Generated by Django 4.0.6 on 2022-07-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_offer_offer_percent_product_product_lining_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photos',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
